# Generated by Django 2.0.4 on 2018-04-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=120)),
                ('opening', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
                ('content', models.CharField(max_length=5000)),
            ],
        ),
    ]
