# Generated by Django 2.0.4 on 2018-06-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('DJBE', 'Django Backend'), ('DJFE', 'Django Frontend'), ('DJU', 'Django Utility'), ('T', 'Technology'), ('A', 'Algorithms'), ('MAKE', 'Arduino and Raspberry Pi'), ('CS', 'Computer Science Fundamentals'), ('PHYS', 'Physics'), ('MAT', 'Math')], default='O', max_length=4),
        ),
    ]
