# Generated by Django 2.0.4 on 2018-06-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='media/blog_content/main-image-photos'),
        ),
    ]
